### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by liuyib** [timqian/follows-you#2]
![image](https://github.com/timqian/follows-you/assets/38221479/c0143d93-16ed-403d-a3d4-386b113a9a2f)
![image](https://github.com/timqian/follows-you/assets/38221479/e8568162-c450-4bfd-94cc-84cb026ea53b)

**Comment by timqian** [comment]
Looks like a network issue or hit the rate limit: GitHub API allows 60 requests/hour

This extension make 2 requests to GitHub API, so in 1 hour, one user can only view 30 users' status

[Ref](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users)

**Comment by liuyib** [comment]
Thx, it's working now

**Comment by factoryfactory** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
4ut0-M-4t, @ddhjy, @L1Cafe, @fyesgo, @bkkwok, @hcxiong, @federicosan, @ansarid, @bryansayler, @parastukh12, @mozillo, @contropist, @lovefawn, @souksou, @kelset, @Gauravsharma-20, @lampard-8, @zorvan, @shinmen-munisai, @meabed, @Ledarium, @StefanRudvin, @volunteer123, @livelybone, @BaloghTamas, @naripok, @hattifnatt4r, @RamonSilva20, @tmprd, @griseyda6, @Stringsaeed, @gtrsh, @adriaanbd, @wk0, @pantaovay, @wuse, @X-Summer, @cbearsy, @taeguk, @brayancruces, @filipeoliveiraa, @jamesmccune6, @usdogu, @christophercelaya, @te0d, @shayanb, @duanyytop, @xuhcc, @rahulkr, @wigust

**Comment by YogaDarma182** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
QArtur99, @SalehBorhani, @lcaraffa, @maxwells8, @jaNGOB, @oguzhan-ulutas, @dvlop, @likaihere, @ykym, @cwali09, @Kana1141, @1453alabanda, @SeavantUUz, @fghcdp, @det-peralta, @xDragonZ, @tugh, @bluebell136, @kurna25, @vdopython, @PatrickRudgeri, @keyboyi, @princesslyons, @IgorYevtushenkoUA, @interboard, @maktubliu, @TimothyL96, @loyal-pelmen, @Havenstd06, @AlexHladin, @vanlinhha, @chairmenfrog, @jakexie, @iluminscode, @cleett, @restuhaqza, @huukhanh, @yimings2072, @qu884j, @leetesla, @JHwebserv, @dtarg16, @shawniac, @wangjianyeART, @ichu468, @LoayGhreep, @sunylkumar, @Kensingtonn, @triswanda22, @ProgrammingLife
